### ISSUE TITLE
Attempting to run xow on DE10 Nano (MiSTer FPGA) - Segmentation fault

### ISSUE THREAD

**Issue by sofakng** [medusalix/xow#124]
I've cross-compiled xow using the Linero toolchain (gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf) but I'm receiving a segmentation fault after it detects the dongle:

```
2020-10-11 02:20:19 INFO  - xow v0.5-16-ga3d2b01 ©Severin v. W.
[New Thread 0xb6cb0430 (LWP 1584)]
2020-10-11 02:20:19 INFO  - Waiting for device...
2020-10-11 02:20:23 DEBUG - Opening device...

Thread 1 "xow" received signal SIGSEGV, Segmentation fault.
0xb6f98ab4 in ?? () from /lib/libusb-1.0.so.0
(gdb) bt
#0  0xb6f98ab4 in ?? () from /lib/libusb-1.0.so.0
#1  0xb6f97c64 in libusb_handle_events_timeout_completed () from /lib/libusb-1.0.so.0
#2  0xb6f98de4 in libusb_bulk_transfer () from /lib/libusb-1.0.so.0
#3  0x00019a8a in UsbDevice::bulkWrite (this=0x37e90, endpoint=endpoint@entry=4 '\004', data=...) at dongle/usb.cpp:141
#4  0x000136a2 in Mt76::loadFirmwarePart (this=this@entry=0xbefff9d0, offset=303360, offset@entry=524288, start=...,
    start@entry=..., end=..., end@entry=...) at dongle/mt76.cpp:1529
#5  0x00013ab2 in Mt76::loadFirmware (this=this@entry=0xbefff9d0) at dongle/mt76.cpp:1464
#6  0x000167fe in Mt76::Mt76 (this=0xbefff9d0, usbDevice=...) at dongle/mt76.cpp:819
#7  0x00018b72 in Dongle::Dongle (this=0xbefff9d0, usbDevice=...) at dongle/dongle.cpp:24
#8  0x0001280c in main () at xow.cpp:88
```

The system (DE10 Nano) uses an ARMv7 CPU and a custom linux kernel.  I couldn't figure out how to black the MT67 kernel module, so I removed support from the kernel completely and recompiled.  (CONFIG_MT76[...]=n)

Can anybody give me a hint of maybe where I need to look to see why this isn't working?

**Comment by sofakng** [comment]
Closing issue and created new issue with better information:  #125
